apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: heroes-api
    team: api
  name: heroes-api
  namespace: api
spec:
  selector:
    matchLabels:
      app: heroes-api
      team: api
  template:
    metadata:
      labels:
        app: heroes-api
        team: api
    spec:
      containers:
      - name: heroes-api
        image: ebriand/conf-cilium-heroes-api:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: KAFKA_BROKERS
          value: my-cluster-kafka-brokers.kafka:9092
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
