apiVersion: v1
kind: Service
metadata:
  labels:
    app: heroes-api
    team: api
  name: heroes-api
  namespace: api
spec:
  selector:
    app: heroes-api
    team: api
  ports:
  - name: http-api
    port: 80