apiVersion: v1
kind: Service
metadata:
  labels:
    app: events-frontend
    team: events
  name: events-frontend
  namespace: events
spec:
  selector:
    app: events-frontend
    team: events
  ports:
  - name: http-frontend
    port: 80