apiVersion: v1
kind: Service
metadata:
  labels:
    app: internal-frontend
    team: internal
  name: internal-frontend
  namespace: internal
spec:
  selector:
    app: internal-frontend
    team: internal
  ports:
  - name: http-frontend
    port: 80