apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-events-kafka
  namespace: kafka
spec:
  endpointSelector:
    matchLabels:
      app: kafka
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: events
        team: events
    toPorts:
    - ports:
      - port: "9092"
        protocol: TCP
      rules:
        kafka:
        - role: produce
          topic: events
        - role: consume
          topic: events
